baseURL = "https://calebclay.com/"
languageCode = "en-us"
title = "Caleb Clay | Technical Builder"
theme = "hugo-blog-awesome"
enableEmoji = true

[menu]
[[menu.main]]
  pageRef = "/"
  name = "Home"
  url = "/"
  weight = 10

[params]
  sitename = "Testing Testing"
  defaultColor = "light"
  description = "More testing here..."

[params.author]
  avatar = "caleb.jpeg"
  intro = "Caleb Clay"
  name = "Caleb Clay"
  description = "Technical Builder"
