baseURL = 'https://calebclay.com/'
languageCode = "en-us"
title = "Caleb Clay | Technical Builder & Writer"
theme = "hugo-blog-awesome"
enableEmoji = true

[menu]
[[menu.main]]
  pageRef = "/"
  name = 'Home'
  url = '/'
  weight = 10
[[menu.main]]
  pageRef = "posts"
  name = 'Posts'
  url = '/posts/'
  weight = 20
[[menu.main]]
  pageRef = "about"
  name = 'About'
  url = '/about/'
  weight = 30

[params]
  sitename = "Caleb Clay"
  defaultColor = "auto"
  description = "Caleb's personal website to share thoughts and showcase work"
  mainSections = ['posts']
  toc = false
  tocOpen = false
  dateFormat = ""
  rssFeedDescription = "summary"

[params.author]
  avatar = "caleb.jpeg"
  intro = "Caleb Clay"
  name = "Caleb Clay"
  description = "Technical Builder & Writer"

[params.webmanifest]
  name = "sitename"
  short_name = "sitename"
  start_url = "/"
  theme_color = "#434648"
  background_color = "fff"
  display = "standalone"
